//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al3ooryCharity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int ID { get; set; }
        public string Photo { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string NationalID { get; set; }
        public Nullable<double> Initial_fees { get; set; }
        public string Email { get; set; }
        public string Social_Status { get; set; }
        public Nullable<int> No__Children { get; set; }
        public string Status { get; set; }
        public string Gender { get; set; }
        public string FName { get; set; }
        public string m1Name { get; set; }
        public string m2Name { get; set; }
        public string LName { get; set; }
        public string comment { get; set; }
    }
}
